-- ============================================================================================
--  Swarnakshi -- hand a restored database to the application role.
--
--  For the case where the database arrived from somewhere else: restored from a pg_dump taken
--  on another machine, or rebuilt on a replacement server. pg_restore makes the role that ran
--  it the owner of everything, which is usually `postgres`, and the application role then owns
--  nothing. It can still log in, but every query fails with "permission denied for table" and
--  the first migration fails with "must be owner of table".
--
--  Run as the postgres superuser, CONNECTED TO THE DATABASE being handed over, after
--  01-create-database.sql has created the role:
--
--      psql -U postgres -h localhost -d cops -v ON_ERROR_STOP=1 -v AppRole="cops_app" -f 04-take-ownership.sql
--
--  Idempotent. Objects already owned by the role produce no statement at all, so running it
--  twice changes nothing the second time.
--
--  It does NOT use REASSIGN OWNED BY postgres TO <role>, which is the obvious one-liner and the
--  wrong tool: REASSIGN also covers shared objects, so on a server hosting more than one
--  application it would hand that role every OTHER database postgres owns as well. This walks
--  the current database only.
--
--  Every statement is generated by a SELECT and run by \gexec. Nothing is inside a DO block,
--  on purpose: psql does not substitute :variables inside dollar-quoted strings, so an AppRole
--  mentioned in one would be taken literally.
-- ============================================================================================

\set ON_ERROR_STOP on

\if :{?AppRole}
\else
  \echo 'Pass the application role with:  -v AppRole="cops_app"'
  DO $$ BEGIN RAISE EXCEPTION 'Required argument missing - see the line above.'; END $$;
\endif

\echo Handing this database to :AppRole

-- ---------- the database and its schema ----------
SELECT format('ALTER DATABASE %I OWNER TO %I', current_database(), :'AppRole')
WHERE (SELECT pg_get_userbyid(datdba) FROM pg_database WHERE datname = current_database()) <> :'AppRole'
\gexec

SELECT format('ALTER SCHEMA public OWNER TO %I', :'AppRole')
WHERE (SELECT nspowner::regrole::text FROM pg_namespace WHERE nspname = 'public') <> :'AppRole'
\gexec

-- ---------- everything in it ----------
-- Tables, sequences, views and materialised views, one statement each. Indexes and constraints
-- follow their table and need no statement of their own.
SELECT format('ALTER %s %I.%I OWNER TO %I',
              CASE c.relkind
                  WHEN 'S' THEN 'SEQUENCE'
                  WHEN 'v' THEN 'VIEW'
                  WHEN 'm' THEN 'MATERIALIZED VIEW'
                  ELSE 'TABLE'
              END,
              n.nspname, c.relname, :'AppRole')
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public'
  AND c.relkind IN ('r', 'p', 'S', 'v', 'm')
  AND pg_get_userbyid(c.relowner) <> :'AppRole'
ORDER BY c.relkind, c.relname
\gexec

-- ---------- report ----------
SELECT pg_get_userbyid(c.relowner) AS owner,
       count(*)                    AS objects
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p', 'S', 'v', 'm')
GROUP BY 1 ORDER BY 1;

\echo Done. Everything above should belong to :AppRole and nothing to anyone else.
